namespace QAHub.Api.Domain.TestDesign;
public sealed class TestCaseVersion
{
 private static readonly Dictionary<TestCaseStatus,TestCaseStatus[]> Transitions=new(){{TestCaseStatus.Draft,[TestCaseStatus.InReview]},{TestCaseStatus.InReview,[TestCaseStatus.Approved,TestCaseStatus.NeedsRevision]},{TestCaseStatus.NeedsRevision,[TestCaseStatus.InReview]},{TestCaseStatus.Approved,[TestCaseStatus.Active,TestCaseStatus.Superseded]},{TestCaseStatus.Active,[TestCaseStatus.Deprecated,TestCaseStatus.Superseded]}};
 private TestCaseVersion(){}
 public TestCaseVersion(Guid testCaseId,int versionNumber,string title,string scenario,string preconditions,string tags){Id=Guid.NewGuid();TestCaseId=testCaseId;VersionNumber=versionNumber;Title=title.Trim();Scenario=scenario.Trim();Preconditions=preconditions.Trim();Tags=tags.Trim();Status=TestCaseStatus.Draft;CreatedAtUtc=UpdatedAtUtc=DateTimeOffset.UtcNow;}
 public Guid Id{get;private set;}public Guid TestCaseId{get;private set;}public int VersionNumber{get;private set;}public string Title{get;private set;}=string.Empty;public string Scenario{get;private set;}=string.Empty;public string Preconditions{get;private set;}=string.Empty;public string Tags{get;private set;}=string.Empty;public TestCaseStatus Status{get;private set;}public DateTimeOffset CreatedAtUtc{get;private set;}public DateTimeOffset UpdatedAtUtc{get;private set;}public List<TestCaseStep> Steps{get;private set;}=[];public List<TestCaseHistoryEntry> History{get;private set;}=[]; public bool IsPotentialDuplicate(string candidateTitle,string candidateScenario){return Normalize(Title)==Normalize(candidateTitle)&&Normalize(Scenario)==Normalize(candidateScenario);} public static string Normalize(string? value)=>string.Join(" ",(value??string.Empty).Trim().ToLowerInvariant().Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries));
 public void Update(string title,string scenario,string preconditions,string tags){if(Status is not TestCaseStatus.Draft and not TestCaseStatus.NeedsRevision)throw new InvalidOperationException("Only draft test case versions can be edited.");Title=title.Trim();Scenario=scenario.Trim();Preconditions=preconditions.Trim();Tags=tags.Trim();UpdatedAtUtc=DateTimeOffset.UtcNow;}
 public void TransitionTo(TestCaseStatus next,string? actorId=null){if(!Transitions.TryGetValue(Status,out var allowed)||!allowed.Contains(next))throw new InvalidOperationException("Invalid test case transition.");Status=next;UpdatedAtUtc=DateTimeOffset.UtcNow;History.Add(new TestCaseHistoryEntry(Id,next,actorId??"system",UpdatedAtUtc));}
}
