"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useState} from "react";
const sections=[
 {title:"Overview",items:[{href:"/",icon:"เนโ€“เธ",label:"Dashboard"},{href:"/products",icon:"เนโ€”ย",label:"Products"}]},
 {title:"Test Management",items:[{href:"/requirements",icon:"เนโ€”ย",label:"Requirements"},{href:"/test-cases",icon:"เนยโ€",label:"Test Cases"},{href:"/execution",icon:"เนโ€“เธ–",label:"Test Execution"},{href:"/bugs",icon:"เนโ€”ย",label:"Bugs"}]},
 {title:"Release",items:[{href:"/releases",icon:"เนยโ€",label:"Build & Release"}]},
 {title:"Utilities",items:[{href:"/toolbox",icon:"เนโ€“เธ",label:"QA Toolbox"}]},
 {title:"Integration",items:[{href:"/integrations",icon:"โ”",label:"Integrations"}]},
 {title:"Administration",items:[{href:"/audit",icon:"เนโ€”ย",label:"Audit History"},{href:"/admin",icon:"เนยย",label:"Users & Roles"}]}
]as const;
export function AppShell({children}:{children:React.ReactNode}){const pathname=usePathname(),[open,setOpen]=useState(false);return <div className="appShell"><aside className={`sidebar ${open?"sidebarOpen":""}`}><Link className="brand" href="/" onClick={()=>setOpen(false)}><span className="brandLogo">QH</span><span><strong>SeniorSoft QA Hub</strong><small>TestOps Platform</small></span></Link><nav aria-label="เน€เธโฌเน€เธเธเน€เธยเน€เธเธเน€เธเธเน€เธเธ…เน€เธเธ‘เน€เธย">{sections.map(section=><div key={section.title}><p className="navTitle">{section.title}</p>{section.items.map(item=><Link className={`navItem ${item.href==="/"?pathname==="/":pathname.startsWith(item.href)?"active":""}`} href={item.href} key={item.label} onClick={()=>setOpen(false)}><i>{item.icon}</i>{item.label}</Link>)}</div>)}</nav><div className="sidebarStatus"><span/><div><strong>Phase 9</strong><small>Integration</small></div></div></aside><button className={`mobileOverlay ${open?"visible":""}`} onClick={()=>setOpen(false)} aria-label="เน€เธยเน€เธเธ”เน€เธโ€เน€เธโฌเน€เธเธเน€เธยเน€เธเธ"/><div className="mainArea"><header className="topbar"><div className="topLeft"><button className="menuButton" onClick={()=>setOpen(true)} aria-label="เน€เธโฌเน€เธยเน€เธเธ”เน€เธโ€เน€เธโฌเน€เธเธเน€เธยเน€เธเธ">เนยเธ</button><label className="search"><span>เนยโ€ข</span><input placeholder="เน€เธยเน€เธยเน€เธยเน€เธเธเน€เธเธ’ Requirement, Test Case, Bug..." disabled/></label></div><div className="profile"><button className="notification" aria-label="เน€เธยเน€เธเธ’เน€เธเธเน€เธยเน€เธยเน€เธยเน€เธยเน€เธโฌเน€เธโ€ขเน€เธเธ—เน€เธเธเน€เธย">เนโ€”ย</button><span><strong>Local Developer</strong><small>System Administrator</small></span><b>LD</b></div></header><div className="content">{children}</div></div></div>}
