import Link from "next/link";
import styles from "./page.module.css";

type Named = { name: string; count: number };
type Trend = { date: string; passed: number; failed: number; blocked: number };
type Work = { assignee: string; testItems: number; openBugs: number };
type Release = { id: string; name: string; status: string; targetDate: string; completed: number; required: number; score: number };
type Product = { id: string; code: string; name: string };
type Dashboard = { activeProducts:number;requirements:number;testCases:number;openBugs:number;criticalHighBugs:number;requirementCoverage:number;execution:{total:number;executed:number;passed:number;failed:number;blocked:number;skipped:number;passRate:number};requirementStatuses:Named[];bugSeverities:Named[];executionTrend:Trend[];workload:Work[];bugAging:{withinSla:number;breached:number;averageAgeDays:number;bands:Named[]};releaseCount:number;averageReleaseReadiness:number;releaseReadiness:Release[] };

export const dynamic = "force-dynamic";

export default async function Home({searchParams}:{searchParams:Promise<{productId?:string}>}) {
  const {productId=""}=await searchParams; let data:Dashboard|null=null,products:Product[]=[];let error:string|null=null;
  try { const query=productId?`?productId=${encodeURIComponent(productId)}`:"";const[d,p]=await Promise.all([fetch(`http://localhost:5120/api/v1/dashboard${query}`,{cache:"no-store"}),fetch("http://localhost:5120/api/v1/products?pageSize=100&isActive=true",{cache:"no-store"})]);if(!d.ok||!p.ok)throw new Error();data=await d.json();products=((await p.json())as{items:Product[]}).items } catch {error="โหลดข้อมูล Dashboard ไม่สำเร็จ"}
  if(!data)return <main><h1>QA Dashboard</h1><p className={styles.error}>{error}</p></main>;
  const query=productId?`?productId=${encodeURIComponent(productId)}`:"";const trendMax=Math.max(1,...data.executionTrend.map(x=>x.passed+x.failed+x.blocked));const metrics=[{label:"Active Products",value:data.activeProducts,tone:"blue"},{label:"Execution Pass Rate",value:`${data.execution.passRate}%`,tone:"green"},{label:"Critical / High Bugs",value:data.criticalHighBugs,tone:"red"},{label:"Release Readiness",value:`${data.averageReleaseReadiness}%`,tone:"orange"}];
  return <main>
    <header className="pageHead"><div><h1>QA Dashboard</h1><p>ภาพรวมคุณภาพจาก transaction จริง พร้อม drill-down รายผลิตภัณฑ์</p></div><div className="pageHeadActions"><a className="statusPill" href={`/backend/v1/dashboard/report${query}`}>Export CSV</a><span className="statusPill">Phase 7 · Reporting</span></div></header>
    <form className={styles.filters}><label>Product<select name="productId" defaultValue={productId}><option value="">All products</option>{products.map(x=><option value={x.id} key={x.id}>{x.code} · {x.name}</option>)}</select></label><button>Apply filter</button>{productId&&<Link href="/">Clear</Link>}</form>
    <section className={styles.metrics}>{metrics.map(x=><article className={`prototypeCard ${styles.metric}`} key={x.label}><div><p>{x.label}</p><h2>{x.value}</h2></div><span className={styles[x.tone]}>●</span></article>)}</section>
    <section className={styles.columns}><article className="prototypeCard"><div className={styles.sectionTitle}><div><h2>Execution trend · 14 days</h2><p>Passed / Failed / Blocked attempts</p></div><Link href={`/execution${query}`}>Drill down →</Link></div><div className={styles.chart}>{data.executionTrend.map(x=><div key={x.date} title={`${x.date}: P${x.passed} F${x.failed} B${x.blocked}`}><i className={styles.pass} style={{height:`${x.passed/trendMax*100}%`}}/><i className={styles.fail} style={{height:`${x.failed/trendMax*100}%`}}/><i className={styles.blocked} style={{height:`${x.blocked/trendMax*100}%`}}/><small>{new Date(x.date).getDate()}</small></div>)}</div></article><article className="prototypeCard"><div className={styles.sectionTitle}><div><h2>Coverage & progress</h2><p>Requirement and execution summary</p></div><Link href={`/requirements${query}`}>Requirements →</Link></div><div className={styles.readiness}><div><span>Requirement coverage</span><strong>{data.requirementCoverage}%</strong></div><div><span>Test Cases</span><strong>{data.testCases}</strong></div><div><span>Executed</span><strong>{data.execution.executed}/{data.execution.total}</strong></div><div><span>Open bugs</span><strong>{data.openBugs}</strong></div></div></article></section>
    <section className={styles.columns}><article className="prototypeCard"><div className={styles.sectionTitle}><div><h2>Bug aging & SLA</h2><p>Open defects requiring attention</p></div><Link href={`/bugs${query}`}>Open Kanban →</Link></div><div className={styles.sla}><div><b>{data.bugAging.withinSla}</b><span>Within SLA</span></div><div className={styles.danger}><b>{data.bugAging.breached}</b><span>SLA breached</span></div><div><b>{data.bugAging.averageAgeDays}</b><span>Average days</span></div></div><div className={styles.bands}>{data.bugAging.bands.map(x=><span key={x.name}>{x.name}<b>{x.count}</b></span>)}</div></article><article className="prototypeCard"><div className={styles.sectionTitle}><div><h2>QA workload</h2><p>Assigned test items and open bugs</p></div></div><div className={styles.workload}>{data.workload.map(x=><div key={x.assignee}><span>{x.assignee}</span><b>{x.testItems} tests · {x.openBugs} bugs</b></div>)}{data.workload.length===0&&<p>No assigned work</p>}</div></article></section>
    <section className={`prototypeCard ${styles.releases}`}><div className={styles.sectionTitle}><div><h2>Release readiness</h2><p>Required checklist completion by release</p></div><Link href={`/releases${query}`}>All releases →</Link></div>{data.releaseReadiness.length===0?<p>No releases</p>:<div className={styles.releaseGrid}>{data.releaseReadiness.slice(0,6).map(x=><Link href={`/releases/${x.id}`} key={x.id}><span><b>{x.name}</b><small>{x.status} · {x.targetDate}</small></span><strong>{x.score}%<small>{x.completed}/{x.required}</small></strong></Link>)}</div>}</section>
  </main>
}
