using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.EntityFrameworkCore;
using QAHub.Api.Domain.Requirements;
using QAHub.Api.Infrastructure.Data;
using QAHub.Api.Infrastructure.Security;
namespace QAHub.Api.Features.Requirements;
public static class RequirementEndpoints
{
 public static IEndpointRouteBuilder MapRequirementEndpoints(this IEndpointRouteBuilder endpoints){var g=endpoints.MapGroup("/api/v1/requirements").WithTags("Requirements").RequireAuthorization(AuthorizationPolicies.ProductAccess);g.MapGet("/",GetAll);g.MapGet("/export",Export);g.MapGet("/{id:guid}",GetOne);g.MapPost("/",Create);g.MapPut("/{id:guid}",Update);g.MapPost("/{id:guid}/transitions",Transition);g.MapGet("/{id:guid}/history",History);g.MapRequirementCollaborationEndpoints();return endpoints;}
 private static async Task<Ok<RequirementCollectionResponse>> GetAll(QAHubDbContext db,Guid? productId,Guid? moduleId,RequirementStatus? status,string? search,int page=1,int pageSize=25,CancellationToken ct=default){page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);var q=db.Requirements.AsNoTracking();if(productId.HasValue)q=q.Where(x=>x.ProductId==productId);if(moduleId.HasValue)q=q.Where(x=>x.ModuleId==moduleId);if(status.HasValue)q=q.Where(x=>x.Status==status);if(!string.IsNullOrWhiteSpace(search)){var term=search.Trim();q=q.Where(x=>x.JobNumber.Contains(term)||x.Title.Contains(term));}var count=await q.CountAsync(ct);var items=await q.OrderByDescending(x=>x.UpdatedAtUtc).Skip((page-1)*pageSize).Take(pageSize).Select(x=>ToResponse(x)).ToListAsync(ct);return TypedResults.Ok(new RequirementCollectionResponse(items,page,pageSize,count));}
 private static async Task<Results<Ok<RequirementResponse>,NotFound>> GetOne(Guid id,QAHubDbContext db,CancellationToken ct){var x=await db.Requirements.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct);return x is null?TypedResults.NotFound():TypedResults.Ok(ToResponse(x));}
 private static async Task<Results<Created<RequirementResponse>,ValidationProblem,Conflict>> Create(CreateRequirementRequest r,QAHubDbContext db,CancellationToken ct){var e=Validate(r.JobNumber,r.Title,r.Description,r.AcceptanceCriteria);if(e.Count>0)return TypedResults.ValidationProblem(e);if(!await db.Products.AnyAsync(x=>x.Id==r.ProductId&&x.IsActive,ct))return TypedResults.ValidationProblem(new Dictionary<string,string[]>{{"productId",["Active product is required."]}});if(r.ModuleId.HasValue&&!await db.ProductModules.AnyAsync(x=>x.Id==r.ModuleId&&x.ProductId==r.ProductId&&x.IsActive,ct))return TypedResults.ValidationProblem(new Dictionary<string,string[]>{{"moduleId",["Module must belong to the selected product."]}});var job=r.JobNumber!.Trim().ToUpperInvariant();if(await db.Requirements.AnyAsync(x=>x.ProductId==r.ProductId&&x.JobNumber==job,ct))return TypedResults.Conflict();var x=new Requirement(r.ProductId,r.ModuleId,job,r.Title!,r.Description!,r.AcceptanceCriteria!,r.Assignee);db.Requirements.Add(x);await db.SaveChangesAsync(ct);return TypedResults.Created($"/api/v1/requirements/{x.Id}",ToResponse(x));}
 private static async Task<Results<Ok<RequirementResponse>,NotFound,ValidationProblem,Conflict>> Update(Guid id,UpdateRequirementRequest r,QAHubDbContext db,CancellationToken ct){var e=Validate("existing",r.Title,r.Description,r.AcceptanceCriteria);if(e.Count>0)return TypedResults.ValidationProblem(e);var x=await db.Requirements.SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return TypedResults.NotFound();if(r.ModuleId.HasValue&&!await db.ProductModules.AnyAsync(m=>m.Id==r.ModuleId&&m.ProductId==x.ProductId&&m.IsActive,ct))return TypedResults.ValidationProblem(new Dictionary<string,string[]>{{"moduleId",["Module must belong to the requirement product."]}});try{x.Update(r.ModuleId,r.Title!,r.Description!,r.AcceptanceCriteria!,r.Assignee);await db.SaveChangesAsync(ct);return TypedResults.Ok(ToResponse(x));}catch(InvalidOperationException){return TypedResults.Conflict();}}
 private static async Task<Results<Ok<RequirementResponse>,NotFound,Conflict>> Transition(Guid id,TransitionRequirementRequest r,QAHubDbContext db,CancellationToken ct){var x=await db.Requirements.SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return TypedResults.NotFound();try{x.TransitionTo(r.Status);await db.SaveChangesAsync(ct);return TypedResults.Ok(ToResponse(x));}catch(InvalidOperationException){return TypedResults.Conflict();}}
 private static async Task<Ok<object>> History(Guid id,QAHubDbContext db,CancellationToken ct){var items=await db.AuditEvents.AsNoTracking().Where(x=>x.EntityType==nameof(Requirement)&&x.EntityId==id).OrderByDescending(x=>x.OccurredAtUtc).Select(x=>new{x.Id,x.OccurredAtUtc,x.ActorId,x.Action,x.ChangesJson}).ToListAsync(ct);return TypedResults.Ok<object>(new{items});}
 private static async Task<IResult> Export(QAHubDbContext db,Guid? productId,RequirementStatus? status,string? search,CancellationToken ct){var q=db.Requirements.AsNoTracking();if(productId.HasValue)q=q.Where(x=>x.ProductId==productId);if(status.HasValue)q=q.Where(x=>x.Status==status);if(!string.IsNullOrWhiteSpace(search)){var term=search.Trim();q=q.Where(x=>x.JobNumber.Contains(term)||x.Title.Contains(term));}var rows=await q.OrderBy(x=>x.JobNumber).Select(x=>new{x.JobNumber,x.Title,x.Status,x.Assignee,x.ProductId,x.ModuleId,x.UpdatedAtUtc}).ToListAsync(ct);static string Csv(object? value)=>$"\"{value?.ToString()?.Replace("\"","\"\"")}\"";var csv=new System.Text.StringBuilder("Job Number,Title,Status,Assignee,Product ID,Module ID,Updated UTC\r\n");foreach(var x in rows)csv.AppendLine(string.Join(',',Csv(x.JobNumber),Csv(x.Title),Csv(x.Status),Csv(x.Assignee),Csv(x.ProductId),Csv(x.ModuleId),Csv(x.UpdatedAtUtc)));return Results.File(System.Text.Encoding.UTF8.GetPreamble().Concat(System.Text.Encoding.UTF8.GetBytes(csv.ToString())).ToArray(),"text/csv",$"requirements-{DateTime.UtcNow:yyyyMMdd}.csv");}
 private static Dictionary<string,string[]> Validate(string? job,string? title,string? description,string? criteria){var e=new Dictionary<string,string[]>();if(string.IsNullOrWhiteSpace(job)||job.Trim().Length>50)e["jobNumber"]=["Job number is required and must not exceed 50 characters."];if(string.IsNullOrWhiteSpace(title)||title.Trim().Length>250)e["title"]=["Title is required and must not exceed 250 characters."];if(string.IsNullOrWhiteSpace(description))e["description"]=["Description is required."];if(string.IsNullOrWhiteSpace(criteria))e["acceptanceCriteria"]=["Acceptance criteria is required."];return e;}
 private static RequirementResponse ToResponse(Requirement x)=>new(x.Id,x.ProductId,x.ModuleId,x.JobNumber,x.Title,x.Description,x.AcceptanceCriteria,x.Assignee,x.Status,x.CreatedAtUtc,x.UpdatedAtUtc);
}
