using System.Security.Claims;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.EntityFrameworkCore;
using QAHub.Api.Domain.Requirements;
using QAHub.Api.Infrastructure.Data;
namespace QAHub.Api.Features.Requirements;
internal static class RequirementCollaborationEndpoints
{
 internal static RouteGroupBuilder MapRequirementCollaborationEndpoints(this RouteGroupBuilder g){g.MapGet("/{id:guid}/comments",GetComments);g.MapPost("/{id:guid}/comments",AddComment);g.MapGet("/{id:guid}/attachments",GetAttachments);g.MapPost("/{id:guid}/attachments",AddAttachment);g.MapGet("/{id:guid}/attachments/{attachmentId:guid}",DownloadAttachment);return g;}
 private static async Task<Results<Ok<IReadOnlyList<RequirementCommentResponse>>,NotFound>> GetComments(Guid id,QAHubDbContext db,CancellationToken ct){if(!await db.Requirements.AnyAsync(x=>x.Id==id,ct))return TypedResults.NotFound();var items=await db.RequirementComments.AsNoTracking().Where(x=>x.RequirementId==id).OrderByDescending(x=>x.CreatedAtUtc).Select(x=>new RequirementCommentResponse(x.Id,x.AuthorId,x.Body,x.CreatedAtUtc)).ToListAsync(ct);return TypedResults.Ok<IReadOnlyList<RequirementCommentResponse>>(items);}
 private static async Task<Results<Created<RequirementCommentResponse>,NotFound,ValidationProblem>> AddComment(Guid id,CreateRequirementCommentRequest r,ClaimsPrincipal user,QAHubDbContext db,CancellationToken ct){if(!await db.Requirements.AnyAsync(x=>x.Id==id,ct))return TypedResults.NotFound();if(string.IsNullOrWhiteSpace(r.Body)||r.Body.Trim().Length>4000)return TypedResults.ValidationProblem(new Dictionary<string,string[]>{{"body",["Comment is required and must not exceed 4000 characters."]}});var x=new RequirementComment(id,user.Identity?.Name??"unknown",r.Body);db.RequirementComments.Add(x);await db.SaveChangesAsync(ct);return TypedResults.Created($"/api/v1/requirements/{id}/comments/{x.Id}",new RequirementCommentResponse(x.Id,x.AuthorId,x.Body,x.CreatedAtUtc));}
 private static async Task<Results<Ok<IReadOnlyList<RequirementAttachmentResponse>>,NotFound>> GetAttachments(Guid id,QAHubDbContext db,CancellationToken ct){if(!await db.Requirements.AnyAsync(x=>x.Id==id,ct))return TypedResults.NotFound();var items=await db.RequirementAttachments.AsNoTracking().Where(x=>x.RequirementId==id).OrderByDescending(x=>x.UploadedAtUtc).Select(x=>new RequirementAttachmentResponse(x.Id,x.FileName,x.ContentType,x.SizeBytes,x.UploadedBy,x.UploadedAtUtc)).ToListAsync(ct);return TypedResults.Ok<IReadOnlyList<RequirementAttachmentResponse>>(items);}
 private static async Task<Results<Created<RequirementAttachmentResponse>,NotFound,ValidationProblem>> AddAttachment(Guid id,CreateRequirementAttachmentRequest r,ClaimsPrincipal user,QAHubDbContext db,CancellationToken ct){if(!await db.Requirements.AnyAsync(x=>x.Id==id,ct))return TypedResults.NotFound();if(string.IsNullOrWhiteSpace(r.FileName)||r.FileName.Trim().Length>255)return TypedResults.ValidationProblem(new Dictionary<string,string[]>{{"fileName",["Valid file name is required."]}});byte[] content;try{content=Convert.FromBase64String(r.ContentBase64??"");}catch(FormatException){return TypedResults.ValidationProblem(new Dictionary<string,string[]>{{"contentBase64",["Invalid Base64 content."]}});}if(content.Length is 0 or > 10_485_760)return TypedResults.ValidationProblem(new Dictionary<string,string[]>{{"contentBase64",["Attachment must be between 1 byte and 10 MB."]}});var safeName=Path.GetFileName(r.FileName);var x=new RequirementAttachment(id,safeName,string.IsNullOrWhiteSpace(r.ContentType)?"application/octet-stream":r.ContentType,content,user.Identity?.Name??"unknown");db.RequirementAttachments.Add(x);await db.SaveChangesAsync(ct);return TypedResults.Created($"/api/v1/requirements/{id}/attachments/{x.Id}",new RequirementAttachmentResponse(x.Id,x.FileName,x.ContentType,x.SizeBytes,x.UploadedBy,x.UploadedAtUtc));}
 private static async Task<Results<FileContentHttpResult,NotFound>> DownloadAttachment(Guid id,Guid attachmentId,QAHubDbContext db,CancellationToken ct){var x=await db.RequirementAttachments.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==attachmentId&&x.RequirementId==id,ct);return x is null?TypedResults.NotFound():TypedResults.File(x.Content,x.ContentType,x.FileName);}
}
