using Microsoft.AspNetCore.Http.HttpResults;using Microsoft.EntityFrameworkCore;using QAHub.Api.Domain.TestDesign;using QAHub.Api.Infrastructure.Data;using QAHub.Api.Infrastructure.Security;
namespace QAHub.Api.Features.TestDesign;
public static class TestCaseEndpoints
{
 public static IEndpointRouteBuilder MapTestCaseEndpoints(this IEndpointRouteBuilder endpoints){var g=endpoints.MapGroup("/api/v1/test-cases").WithTags("Test Cases").RequireAuthorization(AuthorizationPolicies.ProductAccess);g.MapGet("/",GetAll);g.MapGet("/{id:guid}",GetOne);g.MapPost("/",Create);g.MapPost("/{id:guid}/clone",Clone);g.MapPut("/{id:guid}/versions/current",Update);g.MapPost("/{id:guid}/versions/current/transitions",Transition);g.MapPost("/{id:guid}/versions",NewVersion);return endpoints;}
 private static async Task<Ok<TestCaseCollectionResponse>> GetAll(QAHubDbContext db,Guid? productId,Guid? requirementId,TestCaseStatus? status,string? search,int page=1,int pageSize=25,CancellationToken ct=default){page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);var q=from tc in db.TestCases.AsNoTracking()join v in db.TestCaseVersions.AsNoTracking()on new{Id=tc.Id,Version=tc.CurrentVersionNumber}equals new{Id=v.TestCaseId,Version=v.VersionNumber}select new{tc,v};if(productId.HasValue)q=q.Where(x=>x.tc.ProductId==productId);if(requirementId.HasValue)q=q.Where(x=>x.tc.RequirementId==requirementId);if(status.HasValue)q=q.Where(x=>x.v.Status==status);if(!string.IsNullOrWhiteSpace(search)){var term=search.Trim();q=q.Where(x=>x.tc.Code.Contains(term)||x.v.Title.Contains(term)||x.v.Tags.Contains(term));}var count=await q.CountAsync(ct);var items=await q.OrderByDescending(x=>x.v.UpdatedAtUtc).Skip((page-1)*pageSize).Take(pageSize).Select(x=>new TestCaseListItem(x.tc.Id,x.tc.ProductId,x.tc.ModuleId,x.tc.RequirementId,x.tc.Code,x.v.VersionNumber,x.v.Title,x.v.Status,x.v.UpdatedAtUtc)).ToListAsync(ct);return TypedResults.Ok(new TestCaseCollectionResponse(items,page,pageSize,count));}
 private static async Task<Results<Ok<TestCaseResponse>,NotFound>> GetOne(Guid id,QAHubDbContext db,CancellationToken ct){var tc=await db.TestCases.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct);if(tc is null)return TypedResults.NotFound();var v=await db.TestCaseVersions.AsNoTracking().Include(x=>x.Steps).SingleAsync(x=>x.TestCaseId==id&&x.VersionNumber==tc.CurrentVersionNumber,ct);return TypedResults.Ok(ToResponse(tc,v));}
 private static async Task<Results<Created<TestCaseResponse>,ValidationProblem,Conflict>> Create(CreateTestCaseRequest r,QAHubDbContext db,CancellationToken ct){var errors=Validate(r.Code,r.Title,r.Scenario,r.Steps);if(errors.Count>0)return TypedResults.ValidationProblem(errors);if(!await db.Products.AnyAsync(x=>x.Id==r.ProductId&&x.IsActive,ct))return Invalid("productId","Active product is required.");if(r.ModuleId.HasValue&&!await db.ProductModules.AnyAsync(x=>x.Id==r.ModuleId&&x.ProductId==r.ProductId&&x.IsActive,ct))return Invalid("moduleId","Module must belong to product.");if(r.RequirementId.HasValue&&!await db.Requirements.AnyAsync(x=>x.Id==r.RequirementId&&x.ProductId==r.ProductId,ct))return Invalid("requirementId","Requirement must belong to product.");var code=r.Code!.Trim().ToUpperInvariant();if(await db.TestCases.AnyAsync(x=>x.ProductId==r.ProductId&&x.Code==code,ct))return TypedResults.Conflict();var tc=new TestCase(r.ProductId,r.ModuleId,r.RequirementId,code);var v=new TestCaseVersion(tc.Id,1,r.Title!,r.Scenario!,r.Preconditions??"",r.Tags??"");AddSteps(v,r.Steps!);db.TestCases.Add(tc);db.TestCaseVersions.Add(v);await db.SaveChangesAsync(ct);return TypedResults.Created($"/api/v1/test-cases/{tc.Id}",ToResponse(tc,v));}
 private static async Task<Results<Created<TestCaseResponse>,NotFound,Conflict>> Clone(Guid id,QAHubDbContext db,CancellationToken ct){var tc=await db.TestCases.SingleOrDefaultAsync(x=>x.Id==id,ct);if(tc is null)return TypedResults.NotFound();var current=await db.TestCaseVersions.AsNoTracking().Include(x=>x.Steps).SingleAsync(x=>x.TestCaseId==id&&x.VersionNumber==tc.CurrentVersionNumber,ct);var code=await CreateUniqueCloneCodeAsync(tc.ProductId,tc.Code,db,ct);var clone=tc.CloneWithVersion(current,code);db.TestCases.Add(clone);db.TestCaseVersions.Add(clone.Versions.Single());await db.SaveChangesAsync(ct);return TypedResults.Created($"/api/v1/test-cases/{clone.Id}",ToResponse(clone,clone.Versions.Single()));}
 private static async Task<string> CreateUniqueCloneCodeAsync(Guid productId,string sourceCode,QAHubDbContext db,CancellationToken ct){var baseCode=sourceCode.Trim().ToUpperInvariant();var candidate=baseCode;var suffix=1;while(await db.TestCases.AnyAsync(x=>x.ProductId==productId&&x.Code==candidate,ct)){candidate=$"{baseCode}-COPY-{suffix++}";}return candidate;}
 private static async Task<Results<Ok<TestCaseResponse>,NotFound,ValidationProblem,Conflict>> Update(Guid id,UpdateTestCaseVersionRequest r,QAHubDbContext db,CancellationToken ct){var errors=Validate("existing",r.Title,r.Scenario,r.Steps);if(errors.Count>0)return TypedResults.ValidationProblem(errors);var tc=await db.TestCases.SingleOrDefaultAsync(x=>x.Id==id,ct);if(tc is null)return TypedResults.NotFound();var v=await db.TestCaseVersions.Include(x=>x.Steps).SingleAsync(x=>x.TestCaseId==id&&x.VersionNumber==tc.CurrentVersionNumber,ct);try{v.Update(r.Title!,r.Scenario!,r.Preconditions??"",r.Tags??"");db.TestCaseSteps.RemoveRange(v.Steps);v.Steps.Clear();AddSteps(v,r.Steps!);await db.SaveChangesAsync(ct);return TypedResults.Ok(ToResponse(tc,v));}catch(InvalidOperationException){return TypedResults.Conflict();}}
 private static async Task<Results<Ok<TestCaseResponse>,NotFound,Conflict>> Transition(Guid id,TransitionTestCaseRequest r,QAHubDbContext db,CancellationToken ct){var tc=await db.TestCases.SingleOrDefaultAsync(x=>x.Id==id,ct);if(tc is null)return TypedResults.NotFound();var v=await db.TestCaseVersions.Include(x=>x.Steps).SingleAsync(x=>x.TestCaseId==id&&x.VersionNumber==tc.CurrentVersionNumber,ct);try{v.TransitionTo(r.Status);await db.SaveChangesAsync(ct);return TypedResults.Ok(ToResponse(tc,v));}catch(InvalidOperationException){return TypedResults.Conflict();}}
 private static async Task<Results<Created<TestCaseResponse>,NotFound,Conflict>> NewVersion(Guid id,QAHubDbContext db,CancellationToken ct){var tc=await db.TestCases.SingleOrDefaultAsync(x=>x.Id==id,ct);if(tc is null)return TypedResults.NotFound();var current=await db.TestCaseVersions.AsNoTracking().Include(x=>x.Steps).SingleAsync(x=>x.TestCaseId==id&&x.VersionNumber==tc.CurrentVersionNumber,ct);if(current.Status is not TestCaseStatus.Approved and not TestCaseStatus.Active)return TypedResults.Conflict();tc.AdvanceVersion();var v=new TestCaseVersion(tc.Id,tc.CurrentVersionNumber,current.Title,current.Scenario,current.Preconditions,current.Tags);foreach(var x in current.Steps.OrderBy(x=>x.Sequence))v.Steps.Add(new TestCaseStep(v.Id,x.Sequence,x.Action,x.TestData,x.ExpectedResult));db.TestCaseVersions.Add(v);await db.SaveChangesAsync(ct);return TypedResults.Created($"/api/v1/test-cases/{tc.Id}",ToResponse(tc,v));}
 private static void AddSteps(TestCaseVersion v,IReadOnlyList<TestStepRequest> steps){for(var i=0;i<steps.Count;i++)v.Steps.Add(new TestCaseStep(v.Id,i+1,steps[i].Action!,steps[i].TestData??"",steps[i].ExpectedResult!));}
 private static Dictionary<string,string[]> Validate(string? code,string? title,string? scenario,IReadOnlyList<TestStepRequest>? steps){var e=new Dictionary<string,string[]>();if(string.IsNullOrWhiteSpace(code)||code.Trim().Length>50)e["code"]=["Code is required and must not exceed 50 characters."];if(string.IsNullOrWhiteSpace(title)||title.Trim().Length>250)e["title"]=["Title is required."];if(string.IsNullOrWhiteSpace(scenario))e["scenario"]=["Scenario is required."];if(steps is null||steps.Count==0||steps.Any(x=>string.IsNullOrWhiteSpace(x.Action)||string.IsNullOrWhiteSpace(x.ExpectedResult)))e["steps"]=["At least one step with action and expected result is required."];return e;}
 private static ValidationProblem Invalid(string key,string message)=>TypedResults.ValidationProblem(new Dictionary<string,string[]>{{key,[message]}});
 private static TestCaseResponse ToResponse(TestCase tc,TestCaseVersion v)=>new(tc.Id,tc.ProductId,tc.ModuleId,tc.RequirementId,tc.Code,v.VersionNumber,v.Id,v.Title,v.Scenario,v.Preconditions,v.Tags,v.Status,v.Steps.OrderBy(x=>x.Sequence).Select(x=>new TestStepResponse(x.Id,x.Sequence,x.Action,x.TestData,x.ExpectedResult)).ToList(),v.UpdatedAtUtc);
}
