namespace QAHub.Api.Domain.Releases;
public sealed class ReleaseCandidate
{
 private ReleaseCandidate(){}
 public ReleaseCandidate(Guid productId,Guid buildId,Guid environmentId,Guid? testCycleId,string name,DateOnly targetDate,string releaseNotes,string rollbackPlan){if(productId==Guid.Empty||buildId==Guid.Empty||environmentId==Guid.Empty)throw new ArgumentException("Product, build and environment are required.");ArgumentException.ThrowIfNullOrWhiteSpace(name);Id=Guid.NewGuid();ProductId=productId;BuildId=buildId;EnvironmentId=environmentId;TestCycleId=testCycleId;Name=name.Trim();TargetDate=targetDate;ReleaseNotes=releaseNotes.Trim();RollbackPlan=rollbackPlan.Trim();Status=ReleaseStatus.Draft;CreatedAtUtc=UpdatedAtUtc=DateTimeOffset.UtcNow;Checklist.Add(new ReleaseChecklistItem(Id,"release-notes","Release notes reviewed",true));Checklist.Add(new ReleaseChecklistItem(Id,"backup-plan","Backup plan ready",true));Checklist.Add(new ReleaseChecklistItem(Id,"rollback-plan","Rollback plan ready",true));}
 public Guid Id{get;private set;}public Guid ProductId{get;private set;}public Guid BuildId{get;private set;}public Guid EnvironmentId{get;private set;}public Guid? TestCycleId{get;private set;}public string Name{get;private set;}=string.Empty;public DateOnly TargetDate{get;private set;}public string ReleaseNotes{get;private set;}=string.Empty;public string RollbackPlan{get;private set;}=string.Empty;public ReleaseStatus Status{get;private set;}public SignOffDecision? Decision{get;private set;}public string SignOffBy{get;private set;}=string.Empty;public string SignOffReason{get;private set;}=string.Empty;public DateTimeOffset? SignedOffAtUtc{get;private set;}public DateTimeOffset CreatedAtUtc{get;private set;}public DateTimeOffset UpdatedAtUtc{get;private set;}public List<ReleaseChecklistItem> Checklist{get;private set;}=[];
 public void MarkCandidate(){if(Status!=ReleaseStatus.Draft)throw new InvalidOperationException("Only a draft release can become a candidate.");Status=ReleaseStatus.Candidate;UpdatedAtUtc=DateTimeOffset.UtcNow;}
 public void SignOff(SignOffDecision decision,string actor,string reason,bool criticalGatesPassed){if(Status!=ReleaseStatus.Candidate)throw new InvalidOperationException("Only a release candidate can be signed off.");if(decision==SignOffDecision.Approved&&!criticalGatesPassed)throw new InvalidOperationException("Approved sign-off is blocked while critical quality gates fail.");if(decision==SignOffDecision.Conditional&&string.IsNullOrWhiteSpace(reason))throw new InvalidOperationException("Conditional sign-off requires a reason.");Decision=decision;Status=decision switch{SignOffDecision.Approved=>ReleaseStatus.Approved,SignOffDecision.Conditional=>ReleaseStatus.Conditional,_=>ReleaseStatus.Rejected};SignOffBy=actor.Trim();SignOffReason=reason.Trim();SignedOffAtUtc=UpdatedAtUtc=DateTimeOffset.UtcNow;}
}
