using System.Text;
using Microsoft.EntityFrameworkCore;
using QAHub.Api.Domain.Defects;
using QAHub.Api.Domain.Execution;
using QAHub.Api.Infrastructure.Data;
using QAHub.Api.Infrastructure.Security;
#pragma warning disable CA1305
namespace QAHub.Api.Features.Reporting;
public static class DashboardEndpoints
{
 public static IEndpointRouteBuilder MapDashboardEndpoints(this IEndpointRouteBuilder endpoints){var g=endpoints.MapGroup("/api/v1/dashboard").WithTags("Dashboard").RequireAuthorization(AuthorizationPolicies.ProductAccess);g.MapGet("/",Get);g.MapGet("/report",Report);return endpoints;}
 private static async Task<IResult> Get(QAHubDbContext db,Guid? productId,CancellationToken ct)=>Results.Ok(await Build(db,productId,ct));
 private static async Task<IResult> Report(QAHubDbContext db,Guid? productId,CancellationToken ct){var x=await Build(db,productId,ct);var csv=new StringBuilder("Metric,Value\r\n");csv.AppendLine($"Active Products,{x.ActiveProducts}");csv.AppendLine($"Requirements,{x.Requirements}");csv.AppendLine($"Requirement Coverage,{x.RequirementCoverage}%");csv.AppendLine($"Test Cases,{x.TestCases}");csv.AppendLine($"Open Bugs,{x.OpenBugs}");csv.AppendLine($"Critical/High Bugs,{x.CriticalHighBugs}");csv.AppendLine($"Execution Pass Rate,{x.Execution.PassRate}%");csv.AppendLine($"Average Release Readiness,{x.AverageReleaseReadiness}%");return Results.File(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv.ToString())).ToArray(),"text/csv","qa-dashboard-report.csv");}
 private static async Task<DashboardResponse> Build(QAHubDbContext db,Guid? productId,CancellationToken ct)
 {
  var products=db.Products.AsNoTracking().Where(x=>x.IsActive);if(productId.HasValue)products=products.Where(x=>x.Id==productId);var activeProducts=await products.CountAsync(ct);
  var requirements=db.Requirements.AsNoTracking().AsQueryable();var testCases=db.TestCases.AsNoTracking().AsQueryable();var bugs=db.Bugs.AsNoTracking().AsQueryable();var cycles=db.TestCycles.AsNoTracking().Include(x=>x.Items).ThenInclude(x=>x.Attempts).AsSplitQuery().AsQueryable();var releases=db.Releases.AsNoTracking().Include(x=>x.Checklist).AsSplitQuery().AsQueryable();if(productId.HasValue){requirements=requirements.Where(x=>x.ProductId==productId);testCases=testCases.Where(x=>x.ProductId==productId);bugs=bugs.Where(x=>x.ProductId==productId);cycles=cycles.Where(x=>x.ProductId==productId);releases=releases.Where(x=>x.ProductId==productId);}
  var requirementCount=await requirements.CountAsync(ct);var coveredRequirements=await requirements.CountAsync(r=>db.TestCases.Any(tc=>tc.RequirementId==r.Id),ct);var testCaseCount=await testCases.CountAsync(ct);var terminal=new[]{BugStatus.Closed,BugStatus.Rejected,BugStatus.Duplicate,BugStatus.CannotReproduce};var openBugs=await bugs.Where(x=>!terminal.Contains(x.Status)).ToListAsync(ct);var cycleData=await cycles.ToListAsync(ct);var latest=cycleData.SelectMany(c=>c.Items).Select(i=>i.Attempts.OrderBy(a=>a.AttemptNumber).LastOrDefault()).ToList();var executed=latest.Count(x=>x is not null);var passed=latest.Count(x=>x?.Result==ExecutionResult.Passed);var failed=latest.Count(x=>x?.Result==ExecutionResult.Failed);var blocked=latest.Count(x=>x?.Result==ExecutionResult.Blocked);var skipped=latest.Count(x=>x?.Result==ExecutionResult.Skipped);var attempts=cycleData.SelectMany(c=>c.Items).SelectMany(i=>i.Attempts).Where(a=>a.ExecutedAtUtc>=DateTimeOffset.UtcNow.AddDays(-13)).ToList();var trend=Enumerable.Range(0,14).Select(offset=>DateOnly.FromDateTime(DateTime.UtcNow.Date.AddDays(offset-13))).Select(date=>new TrendPoint(date,attempts.Count(a=>DateOnly.FromDateTime(a.ExecutedAtUtc.UtcDateTime)==date&&a.Result==ExecutionResult.Passed),attempts.Count(a=>DateOnly.FromDateTime(a.ExecutedAtUtc.UtcDateTime)==date&&a.Result==ExecutionResult.Failed),attempts.Count(a=>DateOnly.FromDateTime(a.ExecutedAtUtc.UtcDateTime)==date&&a.Result==ExecutionResult.Blocked))).ToList();var testWork=cycleData.SelectMany(c=>c.Items).Where(i=>!string.IsNullOrWhiteSpace(i.Assignee)).GroupBy(i=>i.Assignee).ToDictionary(g=>g.Key,g=>g.Count());var bugWork=openBugs.Where(b=>!string.IsNullOrWhiteSpace(b.Assignee)).GroupBy(b=>b.Assignee).ToDictionary(g=>g.Key,g=>g.Count());var workload=testWork.Keys.Union(bugWork.Keys).Select(name=>new WorkloadItem(name,testWork.GetValueOrDefault(name),bugWork.GetValueOrDefault(name))).OrderByDescending(x=>x.TestItems+x.OpenBugs).Take(10).ToList();var releaseData=await releases.ToListAsync(ct);var readiness=new List<int>();foreach(var release in releaseData){var completed=release.Checklist.Count(i=>i.IsRequired&&i.IsCompleted);var required=release.Checklist.Count(i=>i.IsRequired);readiness.Add((int)Math.Round(DashboardCalculator.Percentage(completed,required)));}
  return new DashboardResponse(activeProducts,requirementCount,testCaseCount,openBugs.Count,openBugs.Count(b=>b.Severity is BugSeverity.Critical or BugSeverity.High),DashboardCalculator.Percentage(coveredRequirements,requirementCount),new ExecutionSummary(latest.Count,executed,passed,failed,blocked,skipped,DashboardCalculator.Percentage(passed,executed)),await requirements.GroupBy(x=>x.Status).Select(g=>new NamedCount(g.Key.ToString(),g.Count())).ToListAsync(ct),openBugs.GroupBy(x=>x.Severity).Select(g=>new NamedCount(g.Key.ToString(),g.Count())).ToList(),trend,workload,releaseData.Count,readiness.Count==0?0:Math.Round(readiness.Average(),1));
 }
}
