using System.Security.Cryptography;using System.Text;using System.Text.Json;using Microsoft.EntityFrameworkCore;using QAHub.Api.Domain.Integrations;using QAHub.Api.Infrastructure.Data;using QAHub.Api.Infrastructure.Security;
namespace QAHub.Api.Features.Integrations;
public sealed record ImportAutomationRunRequest(Guid ProductId,string Provider,string ExternalRunId,string Branch,string CommitSha,string Status,int Total,int Passed,int Failed,int Skipped,string Owner);
public sealed record AutomationRunResponse(Guid Id,Guid ProductId,string Provider,string ExternalRunId,string Branch,string CommitSha,string Status,int Total,int Passed,int Failed,int Skipped,string Owner,DateTimeOffset ReceivedAtUtc);
public sealed record CreateConnectionRequest(Guid? ProductId,string Name,string Provider,string Endpoint,string SecretReference,string Owner);
public static class IntegrationEndpoints
{
 public static IEndpointRouteBuilder MapIntegrationEndpoints(this IEndpointRouteBuilder endpoints){var g=endpoints.MapGroup("/api/v1/integrations").WithTags("Integrations");g.MapGet("/automation-runs",GetAll).RequireAuthorization(AuthorizationPolicies.ProductAccess);g.MapPost("/automation-runs",Import).RequireAuthorization(AuthorizationPolicies.ProductAccess);g.MapPost("/automation/webhook",Webhook).AllowAnonymous();g.MapGet("/connections",GetConnections).RequireAuthorization(AuthorizationPolicies.Administration);g.MapPost("/connections",CreateConnection).RequireAuthorization(AuthorizationPolicies.Administration);g.MapGet("/errors",GetErrors).RequireAuthorization(AuthorizationPolicies.Administration);g.MapPost("/errors/{id:guid}/retry",RetryError).RequireAuthorization(AuthorizationPolicies.Administration);return endpoints;}
 private static async Task<IResult> GetConnections(QAHubDbContext db,CancellationToken ct)=>Results.Ok(await db.IntegrationConnections.AsNoTracking().OrderBy(x=>x.Name).ToListAsync(ct));
 private static async Task<IResult> CreateConnection(CreateConnectionRequest request,QAHubDbContext db,CancellationToken ct){try{if(request.ProductId.HasValue&&!await db.Products.AnyAsync(x=>x.Id==request.ProductId,ct))return Results.ValidationProblem(new Dictionary<string,string[]>{{"productId",["Product does not exist."]}});var x=new IntegrationConnection(request.ProductId,request.Name,request.Provider,request.Endpoint,request.SecretReference,request.Owner);db.IntegrationConnections.Add(x);await db.SaveChangesAsync(ct);return Results.Created($"/api/v1/integrations/connections/{x.Id}",x);}catch(ArgumentException ex){return Results.ValidationProblem(new Dictionary<string,string[]>{{"connection",[ex.Message]}});}}
 private static async Task<IResult> GetErrors(QAHubDbContext db,bool? unresolvedOnly,CancellationToken ct){var q=db.IntegrationErrors.AsNoTracking().AsQueryable();if(unresolvedOnly==true)q=q.Where(x=>!x.IsResolved);return Results.Ok(await q.OrderByDescending(x=>x.CreatedAtUtc).Take(100).ToListAsync(ct));}
 private static async Task<IResult> RetryError(Guid id,QAHubDbContext db,CancellationToken ct){var x=await db.IntegrationErrors.SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return Results.NotFound();x.QueueRetry(DateTimeOffset.UtcNow);await db.SaveChangesAsync(ct);return Results.Ok(x);}
 private static async Task<IResult> GetAll(QAHubDbContext db,Guid? productId,CancellationToken ct){var q=db.AutomationRuns.AsNoTracking().AsQueryable();if(productId.HasValue)q=q.Where(x=>x.ProductId==productId);return Results.Ok(await q.OrderByDescending(x=>x.ReceivedAtUtc).Take(100).Select(x=>Map(x)).ToListAsync(ct));}
 private static Task<IResult> Import(ImportAutomationRunRequest request,QAHubDbContext db,CancellationToken ct)=>ImportCore(request,db,ct);
 private static async Task<IResult> Webhook(HttpRequest http,ImportAutomationRunRequest request,QAHubDbContext db,IConfiguration config,CancellationToken ct){var configured=config["Integrations:AutomationWebhookSecret"];if(string.IsNullOrWhiteSpace(configured))return Results.Problem("Automation webhook is not configured.",statusCode:503);var supplied=http.Headers["X-QAHub-Webhook-Secret"].FirstOrDefault();if(!SecretVerifier.Matches(configured,supplied))return Results.Unauthorized();return await ImportCore(request,db,ct);}
 private static async Task<IResult> ImportCore(ImportAutomationRunRequest request,QAHubDbContext db,CancellationToken ct){if(!await db.Products.AnyAsync(x=>x.Id==request.ProductId,ct))return Results.ValidationProblem(new Dictionary<string,string[]>{{"productId",["Product does not exist."]}});var fingerprint=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(request))));var existing=await db.AutomationRuns.SingleOrDefaultAsync(x=>x.Provider==request.Provider&&x.ExternalRunId==request.ExternalRunId,ct);if(existing is not null){if(existing.Fingerprint==fingerprint)return Results.Ok(Map(existing));db.IntegrationErrors.Add(new IntegrationError(null,"AutomationImport",request.ExternalRunId,"IDEMPOTENCY_CONFLICT","External run ID was retried with different result data.",request.Owner));await db.SaveChangesAsync(ct);return Results.Conflict(new{message="External run ID already exists with different result data."});}try{var run=new AutomationRun(request.ProductId,request.Provider,request.ExternalRunId,request.Branch,request.CommitSha,request.Status,request.Total,request.Passed,request.Failed,request.Skipped,request.Owner,fingerprint);db.AutomationRuns.Add(run);await db.SaveChangesAsync(ct);return Results.Created($"/api/v1/integrations/automation-runs/{run.Id}",Map(run));}catch(ArgumentException ex){return Results.ValidationProblem(new Dictionary<string,string[]>{{"result",[ex.Message]}});}}
 private static AutomationRunResponse Map(AutomationRun x)=>new(x.Id,x.ProductId,x.Provider,x.ExternalRunId,x.Branch,x.CommitSha,x.Status,x.Total,x.Passed,x.Failed,x.Skipped,x.Owner,x.ReceivedAtUtc);
}
public static class SecretVerifier{public static bool Matches(string expected,string? supplied){if(string.IsNullOrEmpty(supplied))return false;var a=SHA256.HashData(Encoding.UTF8.GetBytes(expected));var b=SHA256.HashData(Encoding.UTF8.GetBytes(supplied));return CryptographicOperations.FixedTimeEquals(a,b);}}
