using System.Security.Cryptography;using System.Text;using System.Text.Json;using Microsoft.EntityFrameworkCore;using QAHub.Api.Domain.Integrations;using QAHub.Api.Infrastructure.Data;using QAHub.Api.Infrastructure.Security;
namespace QAHub.Api.Features.Integrations;
public sealed record ImportAutomationRunRequest(Guid ProductId,string Provider,string ExternalRunId,string Branch,string CommitSha,string Status,int Total,int Passed,int Failed,int Skipped,string Owner);
public sealed record AutomationRunResponse(Guid Id,Guid ProductId,string Provider,string ExternalRunId,string Branch,string CommitSha,string Status,int Total,int Passed,int Failed,int Skipped,string Owner,DateTimeOffset ReceivedAtUtc);
public static class IntegrationEndpoints
{
 public static IEndpointRouteBuilder MapIntegrationEndpoints(this IEndpointRouteBuilder endpoints){var g=endpoints.MapGroup("/api/v1/integrations").WithTags("Integrations");g.MapGet("/automation-runs",GetAll).RequireAuthorization(AuthorizationPolicies.ProductAccess);g.MapPost("/automation-runs",Import).RequireAuthorization(AuthorizationPolicies.ProductAccess);g.MapPost("/automation/webhook",Webhook).AllowAnonymous();return endpoints;}
 private static async Task<IResult> GetAll(QAHubDbContext db,Guid? productId,CancellationToken ct){var q=db.AutomationRuns.AsNoTracking().AsQueryable();if(productId.HasValue)q=q.Where(x=>x.ProductId==productId);return Results.Ok(await q.OrderByDescending(x=>x.ReceivedAtUtc).Take(100).Select(x=>Map(x)).ToListAsync(ct));}
 private static Task<IResult> Import(ImportAutomationRunRequest request,QAHubDbContext db,CancellationToken ct)=>ImportCore(request,db,ct);
 private static async Task<IResult> Webhook(HttpRequest http,ImportAutomationRunRequest request,QAHubDbContext db,IConfiguration config,CancellationToken ct){var configured=config["Integrations:AutomationWebhookSecret"];if(string.IsNullOrWhiteSpace(configured))return Results.Problem("Automation webhook is not configured.",statusCode:503);var supplied=http.Headers["X-QAHub-Webhook-Secret"].FirstOrDefault();if(!SecretVerifier.Matches(configured,supplied))return Results.Unauthorized();return await ImportCore(request,db,ct);}
 private static async Task<IResult> ImportCore(ImportAutomationRunRequest request,QAHubDbContext db,CancellationToken ct){if(!await db.Products.AnyAsync(x=>x.Id==request.ProductId,ct))return Results.ValidationProblem(new Dictionary<string,string[]>{{"productId",["Product does not exist."]}});var fingerprint=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(request))));var existing=await db.AutomationRuns.SingleOrDefaultAsync(x=>x.Provider==request.Provider&&x.ExternalRunId==request.ExternalRunId,ct);if(existing is not null)return existing.Fingerprint==fingerprint?Results.Ok(Map(existing)):Results.Conflict(new{message="External run ID already exists with different result data."});try{var run=new AutomationRun(request.ProductId,request.Provider,request.ExternalRunId,request.Branch,request.CommitSha,request.Status,request.Total,request.Passed,request.Failed,request.Skipped,request.Owner,fingerprint);db.AutomationRuns.Add(run);await db.SaveChangesAsync(ct);return Results.Created($"/api/v1/integrations/automation-runs/{run.Id}",Map(run));}catch(ArgumentException ex){return Results.ValidationProblem(new Dictionary<string,string[]>{{"result",[ex.Message]}});}}
 private static AutomationRunResponse Map(AutomationRun x)=>new(x.Id,x.ProductId,x.Provider,x.ExternalRunId,x.Branch,x.CommitSha,x.Status,x.Total,x.Passed,x.Failed,x.Skipped,x.Owner,x.ReceivedAtUtc);
}
public static class SecretVerifier{public static bool Matches(string expected,string? supplied){if(string.IsNullOrEmpty(supplied))return false;var a=SHA256.HashData(Encoding.UTF8.GetBytes(expected));var b=SHA256.HashData(Encoding.UTF8.GetBytes(supplied));return CryptographicOperations.FixedTimeEquals(a,b);}}
