using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using QAHub.Api.Domain.Defects;
using QAHub.Api.Domain.Execution;
using QAHub.Api.Domain.Releases;
using QAHub.Api.Infrastructure.Data;
using QAHub.Api.Infrastructure.Security;
namespace QAHub.Api.Features.Releases;
public static class ReleaseEndpoints
{
 public static IEndpointRouteBuilder MapReleaseEndpoints(this IEndpointRouteBuilder endpoints){var g=endpoints.MapGroup("/api/v1/releases").WithTags("Releases").RequireAuthorization(AuthorizationPolicies.ProductAccess);g.MapGet("/",GetAll);g.MapGet("/{id:guid}",Get);g.MapPost("/",Create);g.MapPut("/{id:guid}/checklist/{itemId:guid}",UpdateChecklist);g.MapPost("/{id:guid}/candidate",MarkCandidate);g.MapPost("/{id:guid}/sign-off",SignOff);return endpoints;}
 private static async Task<IResult> GetAll(QAHubDbContext db,Guid? productId,CancellationToken ct){var q=Query(db);if(productId.HasValue)q=q.Where(x=>x.ProductId==productId);var data=await q.OrderByDescending(x=>x.TargetDate).ToListAsync(ct);var result=new List<ReleaseResponse>();foreach(var x in data)result.Add(await Map(x,db,ct));return Results.Ok(result);}
 private static async Task<IResult> Get(Guid id,QAHubDbContext db,CancellationToken ct){var x=await Query(db).SingleOrDefaultAsync(x=>x.Id==id,ct);return x is null?Results.NotFound():Results.Ok(await Map(x,db,ct));}
 private static async Task<IResult> Create(CreateReleaseRequest r,QAHubDbContext db,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name))return Validation("name","Release name is required.");if(!await db.Products.AnyAsync(x=>x.Id==r.ProductId&&x.IsActive,ct))return Validation("productId","An active product is required.");if(!await db.ProductBuilds.AnyAsync(x=>x.Id==r.BuildId&&x.ProductId==r.ProductId,ct))return Validation("buildId","Build must belong to the product.");if(!await db.ProductEnvironments.AnyAsync(x=>x.Id==r.EnvironmentId&&x.ProductId==r.ProductId&&x.IsActive,ct))return Validation("environmentId","Environment must be active and belong to the product.");if(r.TestCycleId.HasValue&&!await db.TestCycles.AnyAsync(x=>x.Id==r.TestCycleId&&x.ProductId==r.ProductId&&x.BuildId==r.BuildId,ct))return Validation("testCycleId","Test cycle must belong to the product and selected build.");var x=new ReleaseCandidate(r.ProductId,r.BuildId,r.EnvironmentId,r.TestCycleId,r.Name,r.TargetDate,r.ReleaseNotes??"",r.RollbackPlan??"");db.Releases.Add(x);await db.SaveChangesAsync(ct);return Results.Created($"/api/v1/releases/{x.Id}",await Map(x,db,ct));}
 private static async Task<IResult> UpdateChecklist(Guid id,Guid itemId,UpdateChecklistRequest r,ClaimsPrincipal user,QAHubDbContext db,CancellationToken ct){var x=await Query(db).SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return Results.NotFound();var item=x.Checklist.SingleOrDefault(x=>x.Id==itemId);if(item is null)return Results.NotFound();if(x.Status!=ReleaseStatus.Draft)return Results.Conflict(new{message="Checklist can only be changed while release is Draft."});item.SetCompleted(r.IsCompleted,user.Identity?.Name??"unknown");await db.SaveChangesAsync(ct);return Results.Ok(await Map(x,db,ct));}
 private static async Task<IResult> MarkCandidate(Guid id,QAHubDbContext db,CancellationToken ct){var x=await Query(db).SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return Results.NotFound();try{x.MarkCandidate();await db.SaveChangesAsync(ct);return Results.Ok(await Map(x,db,ct));}catch(InvalidOperationException ex){return Results.Conflict(new{message=ex.Message});}}
 private static async Task<IResult> SignOff(Guid id,SignOffRequest r,ClaimsPrincipal user,QAHubDbContext db,CancellationToken ct){var x=await Query(db).SingleOrDefaultAsync(x=>x.Id==id,ct);if(x is null)return Results.NotFound();var model=await Map(x,db,ct);try{x.SignOff(r.Decision,user.Identity?.Name??"unknown",r.Reason??"",model.CanApprove);await db.SaveChangesAsync(ct);return Results.Ok(await Map(x,db,ct));}catch(InvalidOperationException ex){return Results.Conflict(new{message=ex.Message,gates=model.Gates.Where(g=>g.Critical&&!g.Passed)});}}
 private static IQueryable<ReleaseCandidate> Query(QAHubDbContext db)=>db.Releases.Include(x=>x.Checklist).AsSplitQuery();
 private static async Task<ReleaseResponse> Map(ReleaseCandidate x,QAHubDbContext db,CancellationToken ct){var criticalBugs=await db.Bugs.CountAsync(b=>b.ProductId==x.ProductId&&b.Severity==BugSeverity.Critical&&b.Status!=BugStatus.Closed&&b.Status!=BugStatus.Rejected&&b.Status!=BugStatus.Duplicate&&b.Status!=BugStatus.CannotReproduce,ct);TestCycle? cycle=null;if(x.TestCycleId.HasValue)cycle=await db.TestCycles.AsNoTracking().Include(c=>c.Items).ThenInclude(i=>i.Attempts).SingleOrDefaultAsync(c=>c.Id==x.TestCycleId,ct);var latest=cycle?.Items.Select(i=>i.Attempts.OrderBy(a=>a.AttemptNumber).LastOrDefault()).ToList()??[];var gates=new List<GateResponse>{new("critical-bugs","No open Critical bugs",criticalBugs==0,$"{criticalBugs} open",true),new("test-cycle","Test cycle completed",cycle?.Status==TestCycleStatus.Completed,cycle is null?"No cycle selected":cycle.Status.ToString(),true),new("test-results","No failed or blocked latest results",cycle is not null&&latest.All(a=>a?.Result is not ExecutionResult.Failed and not ExecutionResult.Blocked),$"{latest.Count(a=>a?.Result==ExecutionResult.Failed)} failed, {latest.Count(a=>a?.Result==ExecutionResult.Blocked)} blocked",true),new("checklist","Required checklist completed",x.Checklist.Where(i=>i.IsRequired).All(i=>i.IsCompleted),$"{x.Checklist.Count(i=>i.IsRequired&&i.IsCompleted)}/{x.Checklist.Count(i=>i.IsRequired)} complete",true),new("release-plan","Release notes and rollback plan ready",!string.IsNullOrWhiteSpace(x.ReleaseNotes)&&!string.IsNullOrWhiteSpace(x.RollbackPlan),"Release notes and rollback plan",true)};var score=(int)Math.Round(gates.Count(g=>g.Passed)*100d/gates.Count);return new(x.Id,x.ProductId,x.BuildId,x.EnvironmentId,x.TestCycleId,x.Name,x.TargetDate,x.ReleaseNotes,x.RollbackPlan,x.Status,x.Decision,x.SignOffBy,x.SignOffReason,score,gates.Where(g=>g.Critical).All(g=>g.Passed),gates,x.Checklist.Select(i=>new ChecklistResponse(i.Id,i.Code,i.Label,i.IsRequired,i.IsCompleted,i.CompletedBy,i.CompletedAtUtc)).ToList());}
 private static IResult Validation(string key,string message)=>Results.ValidationProblem(new Dictionary<string,string[]>{{key,[message]}});
}
