"use client";
import{FormEvent,useState}from"react";import styles from"./admin.module.css";
type User={id:string;externalId:string;displayName:string;email?:string;isActive:boolean;roles:string[]};type Role={id:string;code:string;name:string;isSystem:boolean};
export function AdminWorkspace({initialUsers,initialRoles,initialError}:{initialUsers:User[];initialRoles:Role[];initialError:string|null}){
 const[users,setUsers]=useState(initialUsers),[roles,setRoles]=useState(initialRoles),[error,setError]=useState(initialError);const[externalId,setExternalId]=useState(""),[displayName,setDisplayName]=useState(""),[roleCode,setRoleCode]=useState(""),[roleName,setRoleName]=useState("");
 async function addUser(e:FormEvent){e.preventDefault();setError(null);const r=await fetch("/backend/v1/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({externalId,displayName})});if(!r.ok){setError("เพิ่มผู้ใช้ไม่สำเร็จ");return}const created=await r.json() as User;setUsers(v=>[...v,{...created,roles:[]}]);setExternalId("");setDisplayName("")}
 async function addRole(e:FormEvent){e.preventDefault();setError(null);const r=await fetch("/backend/v1/admin/roles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:roleCode,name:roleName})});if(!r.ok){setError("เพิ่ม Role ไม่สำเร็จ");return}const created=await r.json() as Role;setRoles(v=>[...v,created]);setRoleCode("");setRoleName("")}
 return <>{error&&<p className={styles.error}>{error}</p>}<div className={styles.grid}><section><h2>Users <b>{users.length}</b></h2><form onSubmit={addUser}><input aria-label="External ID" placeholder="External ID / subject" value={externalId} onChange={e=>setExternalId(e.target.value)} required/><input aria-label="Display name" placeholder="Display name" value={displayName} onChange={e=>setDisplayName(e.target.value)} required/><button>เพิ่ม User</button></form><div className={styles.rows}>{users.map(x=><article key={x.id}><strong>{x.displayName}</strong><span>{x.externalId}</span><small>{x.roles.join(", ")||"No role"}</small></article>)}</div></section><section><h2>Roles <b>{roles.length}</b></h2><form onSubmit={addRole}><input aria-label="Role code" placeholder="Role code" value={roleCode} onChange={e=>setRoleCode(e.target.value)} required/><input aria-label="Role name" placeholder="Role name" value={roleName} onChange={e=>setRoleName(e.target.value)} required/><button>เพิ่ม Role</button></form><div className={styles.rows}>{roles.map(x=><article key={x.id}><strong>{x.name}</strong><span>{x.code}</span><small>{x.isSystem?"System":"Custom"}</small></article>)}</div></section></div></>
}
