@host = http://localhost:5120

GET {{host}}/health

###

GET {{host}}/api/v1/system/info
Accept: application/json
X-Correlation-ID: local-api-test

###

GET {{host}}/api/v1/products?page=1&pageSize=25&isActive=true
Accept: application/json

###

POST {{host}}/api/v1/products
Content-Type: application/json

{
  "code": "PMX",
  "name": "ProMaxx"
}

###

@productId = 00000000-0000-0000-0000-000000000000

GET {{host}}/api/v1/products/{{productId}}/modules?isActive=true
Accept: application/json

###

POST {{host}}/api/v1/products/{{productId}}/modules
Content-Type: application/json

{
  "code": "STK",
  "name": "Stock"
}
