"use client";
import {FormEvent,useState} from "react";
import styles from "../products.module.css";
type Module={id:string;productId:string;code:string;name:string;isActive:boolean};
export function ModulesWorkspace({productId,initialModules}:{productId:string;initialModules:Module[]}){
 const[items,setItems]=useState(initialModules),[code,setCode]=useState(""),[name,setName]=useState(""),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError(null);try{const r=await fetch(`/backend/v1/products/${productId}/modules`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code,name})});if(r.status===409)throw new Error("Module Code นี้มีอยู่แล้ว");if(!r.ok)throw new Error("บันทึก Module ไม่สำเร็จ");const created=await r.json() as Module;setItems(v=>[...v,created].sort((a,b)=>a.code.localeCompare(b.code)));setCode("");setName("")}catch(x){setError(x instanceof Error?x.message:"เกิดข้อผิดพลาด")}finally{setSaving(false)}}
 return <div className={styles.workspace}><form className={styles.form} onSubmit={submit}><div><span className={styles.step}>NEW MODULE</span><h2>เพิ่ม Module</h2></div><label>Module Code<input value={code} onChange={e=>setCode(e.target.value)} maxLength={32} placeholder="STK" required/></label><label>Module Name<input value={name} onChange={e=>setName(e.target.value)} maxLength={200} placeholder="Stock" required/></label><button disabled={saving}>{saving?"กำลังบันทึก...":"เพิ่ม Module"}</button></form><section className={styles.list}><div className={styles.listHead}><div><span className={styles.step}>MODULE DIRECTORY</span><h2>Module ทั้งหมด</h2></div><strong>{items.length}</strong></div>{error&&<p className={styles.error}>{error}</p>}<div className={styles.rows}>{items.map(x=><article key={x.id}><span className={styles.logo}>{x.code.slice(0,2)}</span><div><strong>{x.name}</strong><p>{x.code}</p></div><span className={x.isActive?styles.active:styles.inactive}>{x.isActive?"Active":"Inactive"}</span></article>)}</div>{items.length===0&&<p className={styles.empty}>ยังไม่มี Module</p>}</section></div>
}
